manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson # Or your chosen fork
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: petejohanson # Use the remote defined above
      revision: feat/pointers-move-scroll # Use the branch with pointer support
      import: app/west.yml
  self:
    path: config
